# Generated by Django 3.2.9 on 2021-11-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='imagem',
            field=models.CharField(default='', max_length=255),
        ),
    ]
