# Generated by Django 3.2.9 on 2021-11-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='imagem',
        ),
    ]
